# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
students = [
  {
    role: false,
    first_name: "Cristóbal",
    last_name: "Selame",
    age: 20,
    phone: 62581475,
    address: "Calle Begonias, 321",
    city: "Santiago",
    state: "Santiago",
    country: "Chile",
    studies: "Leyes",
    college: "Gabriela Mistral",
    experience: "",
    languages: "Español, Inglés",
    knowledges: "Leyes comunitarias. Derecho penal",
    email: "cris@pathfinder.com",
    password: "123456"
  },
  {
    role: false,
    first_name: "Juan Manuel",
    last_name: "Binda",
    age: 19,
    phone: 04523153,
    address: "Avenida Cesar, calle Este 84",
    city: "Buenos Aires",
    state: "Buenos Aires",
    country: "Argentina",
    studies: "Marketing",
    college: "Universidad de la Plata",
    experience: "Marketing Digital",
    languages: "Español, Inglés, Francés",
    knowledges: "Marketing Digital",
    email: "juanma@pathfinder.com",
    password: "123456"
  },
  {
    role: false,
    first_name: "Hugo",
    last_name: "Acosta",
    age: 20,
    phone: 65842519,
    address: "Calle Genesis, 12",
    city: "Santa Cruz de la Sierra",
    state: "Santa Cruz",
    country: "Bolivia",
    studies: "Ingeniería Informática",
    college: "UAGRM",
    experience: "Desarrollo de software de gestión. Proyecto de grado",
    languages: "Español, Inglés",
    knowledges: "PHP, HTML y CSS",
    email: "hugo@pathfinder.com",
    password: "123456"
  },
  {
    role: false,
    first_name: "Sergio",
    last_name: "Andrade",
    age: 18,
    phone: 21748130,
    address: "Avenida Santos, Calle General Bold # 298",
    city: "Buenos Aires",
    state: "Buenos Aires",
    country: "Argentina",
    studies: "Ingeniería Industrial",
    college: "Universidad de Buenos Aires",
    experience: "Creación de muebles con impresora 3D",
    languages: "Español",
    knowledges: "Mécanica",
    email: "sergand@gmail.com",
    password: "123456"
  },
  {
    role: false,
    first_name: "Verónica",
    last_name: "Soria",
    age: 20,
    phone: 87541926,
    address: "Av. Costanera, Central Plaza 271",
    city: "Santiago de Chile",
    state: "Santiago",
    country: "Chile",
    studies: "Gastronomía",
    college: "UDLC",
    experience: "",
    languages: "Español, Francés",
    knowledges: "Platos típicos. Platos Internacionales",
    email: "verosor@gmail.com",
    password: "123456"
  },
  {
    role: false,
    first_name: "Florencia",
    last_name: "Estrada",
    age: 19,
    phone: 54713964,
    address: "Calle Intersección, 78",
    city: "Buenos Aires",
    state: "Buenos Aires",
    country: "Argentina",
    studies: "Leyes",
    college: "UEDP",
    experience: "",
    languages: "Español, Inglés",
    knowledges: "Derecho Laboral",
    email: "flor3214@gmail.com",
    password: "123456"
  },
  {
    role: false,
    first_name: "Cecilia",
    last_name: "Rosado",
    age: 18,
    phone: 58431649,
    address: "Avenida Mutual, calle Salomon",
    city: "Cochabamba",
    state: "Cochabamba",
    country: "Bolivia",
    studies: "Marketing",
    college: "UNIVALLE",
    experience: "",
    languages: "Español, Inglés",
    knowledges: "Posicionamiento de Marca",
    email: "ceci8712@gmail.com",
    password: "123456"
  },
  {
    role: false,
    first_name: "Andres",
    last_name: "Segundo",
    age: 20,
    phone: 54173968,
    address: "Calle Real, Nro. 742",
    city: "Rosario",
    state: "Santa Fe",
    country: "Argentina",
    studies: "Contaduría Pública",
    college: "URSF",
    experience: "",
    languages: "Español",
    knowledges: "Auditoría Interna",
    email: "andrreseg@gmail.com",
    password: "123456"
  },
  {
    role: false,
    first_name: "Rosario",
    last_name: "Ayala",
    age: 21,
    phone: 30152849,
    address: "Calle Gral. Cruz # 15",
    city: "Concepción",
    state: "Concepción",
    country: "Chile",
    studies: "Arquitectura",
    college: "Universidad de Concepción",
    experience: "",
    languages: "Español",
    knowledges: "Diseño",
    email: "rosa12@gmail.com",
    password: "123456"
  },
  {
    role: false,
    first_name: "Julio",
    last_name: "Soliz",
    age: 22,
    phone: 87490317,
    address: "Av. Padro # 162",
    city: "La Paz",
    state: "La Paz",
    country: "Bolivia",
    studies: "Administración de Empresas",
    college: "UMSS",
    experience: "",
    languages: "Español",
    knowledges: "Recursos Humanos",
    email: "solizj12@gmail.com",
    password: "123456"
  },
  {
    role: false,
    first_name: "German",
    last_name: "Rocha",
    age: 21,
    phone: 85914627,
    address: "Avenida República, Calle Victoria, # 54",
    city: "Osorno",
    state: "Los Lagos",
    country: "Chile",
    studies: "Ingeniería Comercial",
    college: "UNOS",
    experience: "",
    languages: "Español",
    knowledges: "Comercio Internacional",
    email: "germanr981@gmail.com",
    password: "123456"
  },
  {
    role: false,
    first_name: "Raquel",
    last_name: "Rocha",
    age: 22,
    phone: 48503018,
    address: "Avenida Rio Negro # 271",
    city: "Córdoba",
    state: "Córdoba",
    country: "Argentina",
    studies: "Administración de Empresas",
    college: "UNACO",
    experience: "",
    languages: "Español, Inglés",
    knowledges: "Administración Financiera",
    email: "raquelroch@gmail.com",
    password: "123456"
  },
  {
    role: false,
    first_name: "Julio",
    last_name: "Roman",
    age: 21,
    phone: 54130470,
    address: "Calle Bartenes # 192",
    city: "Montevideo",
    state: "Montevideo",
    country: "Uruguay",
    studies: "Ingeniería de Sistemas",
    college: "FAUR",
    experience: "",
    languages: "Español",
    knowledges: "Desarrollo con Python",
    email: "julicor12@gmail.com",
    password: "123456"
  },
  {
    role: false,
    first_name: "Cristina",
    last_name: "Aponte",
    age: 19,
    phone: 26010045,
    address: "Calle Pastaza # 53",
    city: "Arequipa",
    state: "Arequipa",
    country: "Perú",
    studies: "Ingeniería Petrolera",
    college: "UNADA",
    experience: "",
    languages: "Español",
    knowledges: "Refinamiento",
    email: "crisap721@gmail.com",
    password: "123456"
  },
  {
    role: false,
    first_name: "Sofia",
    last_name: "Mercado",
    age: 22,
    phone: 50180345,
    address: "Av. San Martín, calle Ruet 213",
    city: "Lima",
    state: "Lima",
    country: "Perú",
    studies: "Comercio Internacional",
    college: "UANLI",
    experience: "",
    languages: "Español, Inglés",
    knowledges: "Relaciones Internacionales",
    email: "sofim78@gmail.com",
    password: "123456"
  },
  {
    role: false,
    first_name: "Marcelo",
    last_name: "Rincón",
    age: 18,
    phone: 66944204,
    address: "Calle Jerusalen # 78",
    city: "Asunción",
    state: "Asunción",
    country: "Paraguay",
    studies: "Ingeniería Civil",
    college: "UNAS",
    experience: "",
    languages: "Español, Inglés",
    knowledges: "Fluidos y flujos",
    email: "marcerin@gmail.com",
    password: "123456"
  },
  {
    role: false,
    first_name: "Marcos",
    last_name: "Nuva",
    age: 22,
    phone: 22554871,
    address: "Avenida Merin, calle Norte, # 15",
    city: "Tarija",
    state: "Tarija",
    country: "Bolivia",
    studies: "Trabajo Social",
    college: "UNJMS",
    experience: "",
    languages: "Español, Inglés",
    knowledges: "Apoyo Sectorial",
    email: "nuvamarc@gmail.com",
    password: "123456"
  },
  {
    role: false,
    first_name: "Ruben",
    last_name: "Tejerina",
    age: 21,
    phone: 26003314,
    address: "Calle Recoleta, Nro. 81",
    city: "Asunción",
    state: "Asunción",
    country: "Paraguay",
    studies: "Economía",
    college: "UNAS",
    experience: "",
    languages: "Español",
    knowledges: "Auditoría Impositiva",
    email: "tejrub87@gmail.com",
    password: "123456"
  },
  {
    role: false,
    first_name: "Alba",
    last_name: "Barrientos",
    age: 23,
    phone: 30201145,
    address: "Calle Manza. Oeste # 8123",
    city: "Guayaquil",
    state: "Guayaquil",
    country: "Ecuador",
    studies: "Ingeniería de Alimentos",
    college: "Universidad de Guayaquil",
    experience: "",
    languages: "Español, Inglés",
    knowledges: "Procesamiento Alimentario",
    email: "barralb3@gmail.com",
    password: "123456"
  },
  {
    role: false,
    first_name: "Willy",
    last_name: "Suarez",
    age: 21,
    phone: 65487244,
    address: "Av. Rubio, calle San Bernardo # 84",
    city: "Quito",
    state: "Quito",
    country: "Ecuador",
    studies: "Administración de Empresas",
    college: "UNAQ",
    experience: "",
    languages: "Español",
    knowledges: "Recursos Humanos, Desarrollo Humano",
    email: "willys83@gmail.com",
    password: "123456"
  }
]

students.each do |s|
  User.create!(s)
end

puts "Students creados"

puts "Creando Companies"
company = [
  {
    role: true,
    phone: 12512345678,
    address: "Calle Principal 142",
    city: "Ciudad de México",
    state: "Ciudad de México",
    country: "México",
    name: "TechNode",
    website: "https://www.technode.com",
    industry: "Tecnología",
    about: "TechNode es una empresa de tecnología líder en el desarrollo de soluciones innovadoras."
  },
  {
    role: true,
    phone: 2298765432,
    address: "Avenida General Oviedo 456",
    city: "Santiago",
    state: "Región Metropolitana",
    country: "Chile",
    name: "IndusTreck",
    website: "https://www.industreck.cl",
    industry: "Manufactura",
    about: "Industreck es una destacada empresa de fabricación que produce bienes de consumo de alta calidad."
  },
  {
    role: true,
    phone: 35156755482,
    address: "Rua Paulo 789",
    city: "São Paulo",
    state: "São Paulo",
    country: "Brasil",
    name: "Servi Create",
    website: "https://www.servicreate.com.br",
    industry: "Servicios",
    about: "Servi Create es una empresa de servicios dedicada a brindar soluciones integrales para sus clientes."
  },
  {
    role: true,
    phone: 441197314722,
    address: "Calle Cuadradi 789",
    city: "Buenos Aires",
    state: "Buenos Aires",
    country: "Argentina",
    name: "Consult Range",
    website: "https://www.consultrange.com.ar",
    industry: "Consultoría",
    about: "Consul Range es una empresa de consultoría especializada en estrategias de negocios y desarrollo organizacional."
  },
  {
    role: true,
    phone: 5715215894,
    address: "Carrera Costaner 43",
    city: "Bogotá",
    state: "Cundinamarca",
    country: "Colombia",
    name: "EcoModa",
    website: "https://www.ecomoda.co",
    industry: "Moda",
    about: "EcoModa es una empresa líder en el sector de la moda, ofreciendo prendas de vestir de alta calidad y diseño vanguardista."
  },
  {
    role: true,
    phone: 6036295283,
    address: "Avenida Diametral 14",
    city: "San Salvador",
    state: "San Salvador",
    country: "El Salvador",
    name: "AliTron",
    website: "https://www.alitron.com.sv",
    industry: "Alimentación",
    about: "Alitron es una empresa dedicada a la producción y distribución de alimentos frescos y saludables para el mercado local e internacional."
  },
  {
    role: true,
    phone: 70105428472,
    address: "Calle Soleto 789",
    city: "San José",
    state: "San José",
    country: "Costa Rica",
    name: "EcoTuris",
    website: "https://www.ecoturis.co.cr",
    industry: "Turismo",
    about: "EcoTuris es una agencia de viajes que ofrece experiencias turísticas inolvidables en los destinos más hermosos de Costa Rica."
  },
  {
    role: true,
    phone: 8911023457,
    address: "Avenida Bartolome 84",
    city: "Santa Cruz",
    state: "Santa Cruz",
    country: "Bolivia",
    name: "EnergySun",
    website: "https://www.energysun.bo",
    industry: "Energía",
    about: "EnergySun es una empresa especializada en el desarrollo y suministro de soluciones energéticas sostenibles para el sector industrial."
  }
]

company.each do |c|
  User.create(c)
end


puts "Companies creadas"

puts "Creando Internships"
internships = [
  {
    category: "Tecnología",
    title: "Desarrollador FrontEnd",
    description: "Pasantía para desarrollar el frontend de aplicaciones web. Conocimientos en HTML, CSS y Javascript",
    tipo: "Remoto",
    status: true,
    duration: 6,
    paid: "Paga",
    start_date: "2023/06/08",
    end_date: "2023/07/08",
    user_id: 21
  },
  {
    category: "Manufactura",
    title: "Comercio Internacional",
    description: "Llevar adelante las relaciones de comercio con empresas proveedoras y distribuidoras de la marca",
    tipo: "Remoto",
    status: true,
    duration: 10,
    paid: "Paga",
    start_date: "2023/06/20",
    end_date: "2023/07/30",
    user_id: 22
  },
  {
    category: "Servicios",
    title: "Administrador Contable",
    description: "Organizar y controlar la contabilidad de la empresa",
    tipo: "Remoto",
    status: true,
    duration: 6,
    paid: "Paga",
    start_date: "2023/06/21",
    end_date: "2023/08/10",
    user_id: 23
  },
  {
    category: "Consultoría",
    title: "Consultor Financiero",
    description: "Analizar y fiscalizar las finanzas",
    tipo: "Presencial",
    status: true,
    duration: 9,
    paid: "Paga",
    start_date: "2023/06/01",
    end_date: "2023/06/30",
    user_id: 24
  },
  {
    category: "Moda",
    title: "Marketing Digital",
    description: "Llevar adelante el marketing digital de los nuevos productos",
    tipo: "Remoto",
    status: true,
    duration: 10,
    paid: "Paga",
    start_date: "2023/06/10",
    end_date: "2023/07/20",
    user_id: 25
  },
  {
    category: "Alimentos",
    title: "Control de Calidad",
    description: "Programar y organizar el proceso de control de calidad",
    tipo: "Presencial",
    status: true,
    duration: 10,
    paid: "Paga",
    start_date: "2023/06/15",
    end_date: "2023/07/01",
    user_id: 26
  },
  {
    category: "Turismo",
    title: "Desarrollador Web",
    description: "Desarrollar nuestro sitio web como aplicación",
    tipo: "Remoto",
    status: true,
    duration: 8,
    paid: "Paga",
    start_date: "2023/06/01",
    end_date: "2023/07/30",
    user_id: 27
  },
  {
    category: "Energía",
    title: "Derecho Laboral",
    description: "Elaborar guía para elaboración del cumpliento de los derecho laborales",
    tipo: "Remoto",
    status: true,
    duration: 6,
    paid: "Paga",
    start_date: "2023/06/01",
    end_date: "2023/06/30",
    user_id: 28
  }
]

internships.each do |i|
  Internship.create(i)
end

puts "Internships creadas"
